In [1]:
!pip install transformers==4.36.1 xformers einops accelerate==0.21.0 langchain bitsandbytes==0.40.2 sentencepiece peft==0.4.0 trl==0.4.7 codecarbon

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.8/126.8 kB 3.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 54.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.2/244.2 kB 17.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.5/92.5 MB 18.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.9/72.9 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.4/77.4 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 218.2/218.2 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 80.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 62.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.

In [2]:
import huggingface_hub
hf_token = "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"
huggingface_hub.login(token=hf_token, add_to_git_credential=True)

Token is valid (permission: write).
Cannot authenticate through git-credential as no helper is defined on your machine.
You might have to re-authenticate when pushing to the Hugging Face Hub.
Run the following command in your terminal in case you want to set the 'store' credential helper as default.

git config --global credential.helper store

Read https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage for more details.
Token has not been saved to git credential helper.
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [3]:
from langchain import HuggingFacePipeline
from transformers import AutoTokenizer, AutoModelForCausalLM, GenerationConfig
import transformers
import torch
import warnings
warnings.filterwarnings('ignore')
import locale
locale.getpreferredencoding = lambda: "UTF-8"

/opt/conda/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(


In [4]:
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

base_model = AutoModelForCausalLM.from_pretrained('meta-llama/Llama-2-7b-hf', load_in_8bit=True, device_map="auto")
base_model.resize_token_embeddings(260164)
tokenizer = AutoTokenizer.from_pretrained('MaLA-LM/mala-500')
model = PeftModel.from_pretrained(base_model, 'MaLA-LM/mala-500')


2024-03-07 11:45:37.289670: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-07 11:45:37.289772: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-07 11:45:37.415962: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


config.json:   0%|          | 0.00/609 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.38k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.46M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

adapter_config.json:   0%|          | 0.00/528 [00:00<?, ?B/s]

adapter_model.bin:   0%|          | 0.00/4.27G [00:00<?, ?B/s]

In [5]:
pipeline = transformers.pipeline(
    "text-generation", #task
    model=model,
    tokenizer=tokenizer,
    torch_dtype= "auto",
    trust_remote_code=True,
    device_map="auto",
    max_length=1000,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id

)

The model 'PeftModelForCausalLM' is not supported for text-generation. Supported models are ['BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'CamembertForCausalLM', 'LlamaForCausalLM', 'CodeGenForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'Data2VecTextForCausalLM', 'ElectraForCausalLM', 'ErnieForCausalLM', 'FalconForCausalLM', 'FuyuForCausalLM', 'GitForCausalLM', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GPTJForCausalLM', 'LlamaForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegaForCausalLM', 'MegatronBertForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'MptForCausalLM', 'MusicgenForCausalLM', 'MvpForCausalLM', 'OpenLlamaForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PersimmonF

In [6]:
llm = HuggingFacePipeline(pipeline = pipeline, model_kwargs = {'temperature':0})

In [7]:
from langchain import PromptTemplate, LLMChain

template = """ <s> [INST] <<SYS>>
You are a Bengali text classifier.
<</SYS>>
What is the author's sentiment of the provided comment? "{text}".
a. "negative" or, b. "positive" or, c."neutral"
You should only choose. No  extra lines. No need to tell anything else.
Format the output only as JSON with the following key:
class
[/INST] </s>
"""
prompt = PromptTemplate(template=template, input_variables=["text"])
llm_chain = LLMChain(prompt=prompt, llm=llm)

In [8]:
text = "আইসিসিকে এই তথ্য দিলো কে?শুওরের বাচ্চা পাপন"
print(llm_chain(text))

{'text': "### What Is A Fixed Annuity?\n\nFixed annuities are insurance products that pay a fixed amount each year for the rest of your life, and then to your beneficiaries after you pass away. They are a great way to create a guaranteed income stream that lasts for your entire life and beyond.\n\n### Why Buy A Fixed Annuity?\n\nFixed annuities are great for retirees who want to create a guaranteed income stream that lasts for the rest of their life. The fixed annuity pays out a guaranteed amount each year, which is great for retirees who don't want to worry about their income stream changing.\n\n### How Do Fixed Annuities Work?\n\nFixed annuities are insurance products that pay a fixed amount each year for the rest of your life, and then to your beneficiaries after you pass away. They are a great way to create a guaranteed income stream that lasts for your entire life and beyond.\n\n### What Is The Difference Between Fixed Annuities And Fixed Index Annuities?\n\nFixed annuities are in

In [9]:
text = "১৯৩১ সালের ১৮ আগস্ট যুক্তরাষ্ট্রের নিউ জার্সি অঙ্গরাজ্যের হেনরি বোসেনবার্গ গোলাপের নতুন একটি জাত আবিষ্কারের জন্য একটি পেটেন্ট পান। "
print(llm_chain(text))

{'text': '### 1. What is the difference between a 1st-order and a 2nd-order differential equation?\n\n### 2. What are the main differences between the solutions of the two types of equations?\n\n### 3. What is the difference between the solutions of the two types of equations in the case of an initial condition?\n\n### 4. What is the difference between the solutions of the two types of equations in the case of a boundary condition?\n\n### 5. How can you solve a second-order differential equation with a boundary condition?\n\n### 6. How can you solve a second-order differential equation with an initial condition?\n\n### 7. How can you solve a second-order differential equation with both an initial condition and a boundary condition?\n\n### 8. How can you solve a second-order differential equation with an initial condition and a boundary condition?\n\n### 9. How can you solve a second-order differential equation with an initial condition and two boundary conditions?\n\n### 10. How can yo

In [10]:
text = "অমায়িক ব্যবহার এই রেস্টুরেন্টের স্টাফদের"
print(llm_chain(text))

{'text': '\n### 02/04/2021\n\n### 03/04/2021\n\n### 04/04/2021\n\n### 05/04/2021\n\n### 06/04/2021\n\n### 07/04/2021\n\n### 08/04/2021\n\n### 09/04/2021\n\n### 10/04/2021\n\n### 11/04/2021\n\n### 12/04/2021\n\n### 13/04/2021\n\n### 14/04/2021\n\n### 15/04/2021\n\n### 16/04/2021\n\n### 17/04/2021\n\n### 18/04/2021\n\n### 19/04/2021\n\n### 20/04/2021\n\n### 21/04/2021\n\n### 22/04/2021\n\n### 23/04/2021\n\n### 24/04/2021\n\n### 25/04/2021\n\n### 26/04/2021\n\n### 27/04/2021\n\n### 28/04/2021\n\n### 29/04/2021\n\n### 30/04/2021\n\n### 31/04/2021\n\n### 32/04/2021\n\n### 33/04/2021\n\n### 34/04/2021\n\n### 35/04/2021\n\n### 36/04/2021\n\n### 37/04/2021\n\n### 38/04/2021\n\n### 39/04/2021\n\n### 40/04/2021\n\n### 41/04/2021\n\n### 42/04/2021\n\n### 43/04/2021\n\n### 44/04/2021\n\n### 45/04/2021\n\n### 46/04/2021\n\n### 47/04/2021\n\n### 48/04/2021\n\n### 49/04/2021\n\n### 50/04/2021\n\n### 51/04/2021\n\n### 52/04/2021\n\n### 53/04/2021\n\n### 54/04/2021\n\n### 55/04/2021\n\n### 56/04/2021\n

In [11]:
text = "আগারওয়াল পিউর বাস্টার্ড এর কিছু হবে না???"
print(llm_chain(text))

{'text': '### 100th Anniversary\n\n### 1st Anniversary\n\n### 2nd Anniversary\n\n### 3rd Anniversary\n\n### 4th Anniversary\n\n### 5th Anniversary\n\n### 6th Anniversary\n\n### 7th Anniversary\n\n### 8th Anniversary\n\n### 9th Anniversary\n\n### 10th Anniversary\n\n### 11th Anniversary\n\n### 12th Anniversary\n\n### 13th Anniversary\n\n### 14th Anniversary\n\n### 15th Anniversary\n\n### 16th Anniversary\n\n### 17th Anniversary\n\n### 18th Anniversary\n\n### 19th Anniversary\n\n### 20th Anniversary\n\n### 21st Anniversary\n\n### 22nd Anniversary\n\n### 23rd Anniversary\n\n### 24th Anniversary\n\n### 25th Anniversary\n\n### 26th Anniversary\n\n### 27th Anniversary\n\n### 28th Anniversary\n\n### 29th Anniversary\n\n### 30th Anniversary\n\n### 31st Anniversary\n\n### 32nd Anniversary\n\n### 33rd Anniversary\n\n### 34th Anniversary\n\n### 35th Anniversary\n\n### 36th Anniversary\n\n### 37th Anniversary\n\n### 38th Anniversary\n\n### 39th Anniversary\n\n### 40th Anniversary\n\n### 41st Anniv

In [12]:
text = "আমার টুরিস্ট ভিসা রোগীর সাথে যেতে পারবো তাকে দেখাশুনা করার জন্য"
print(llm_chain(text))

{'text': '#ifndef BLE_SERVER_H\n#define BLE_SERVER_H\n#include <Arduino.h>\n#include "BleDevice.h"\n#include "BleServer.h"\n#include "BleClient.h"\n#include "BleConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleDeviceConnection.h"\n#include "BleDeviceConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include "BleServerConnection.h"\n#include

In [13]:
def llama2_hs(text):
    return {'llama2_output' : llm_chain(text)}

In [14]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/SentNoB Dataset/Val.csv
/kaggle/input/SentNoB Dataset/Train.csv
/kaggle/input/SentNoB Dataset/Test.csv


In [15]:
import pandas as pd
df_test = pd.read_csv('/kaggle/input/SentNoB Dataset/Test.csv', delimiter=',', encoding='utf-8')
#df_test = pd.read_excel('/kaggle/input/bd-shs-test-english-data-google-translated/HS test dataset into english by google translator.xlsx')
df_test

Data  Label
0     স্বাস্থ্যবান হতে চাই , আমি বয়সের তুলনায় অনেক ব...      0
1                           ভাইয়া নতুন ভিডিও আসে না কেন      0
2           সৌরভ গাঙ্গুলী ছাড়া দাদাগিরি কখনো জমে উঠত না      0
3     ক্রিকেট কে বাচাতে হলে পাপকে অতিশিগ্রিই তাকেও গ...      2
4                             আমিতো সেই ঝালপ্রিয়ো মানুষ      1
...                                                 ...    ...
1581       ঐ পুলিশ কুওারবাচচাদের গুলিকরে মেরে ফেলা উচিত      2
1582   খিচুড়ি পর্ব মারাত্মক । বাকি টা দেখি তারপর কমেন্ট      1
1583                   পাশের ফ্রেন্ডটা কি ছেলে না মেয়ে       2
1584        মদ লকমান না খেলেও আমরা খাই এমনটাই মনে হচ্ছে      2
1585  এইসমস্ত হায়েনা দের কোনো জেল না দিয়ে ফাঁসি দিয়ে...      2

[1586 rows x 2 columns]

In [16]:
import datasets
dataset = datasets.Dataset.from_pandas(df_test)

In [17]:
dataset = dataset.shuffle(seed=42)
sample_test_dataset = dataset.select(range(20))

In [18]:
!pip install -q codecarbon
from codecarbon import EmissionsTracker
tracker = EmissionsTracker()

[codecarbon INFO @ 12:05:36] [setup] RAM Tracking...
[codecarbon INFO @ 12:05:36] [setup] GPU Tracking...
[codecarbon INFO @ 12:05:36] Tracking Nvidia GPU via pynvml
[codecarbon INFO @ 12:05:36] [setup] CPU Tracking...
[codecarbon WARNING @ 12:05:36] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon WARNING @ 12:05:37] We saw that you have a Intel(R) Xeon(R) CPU @ 2.00GHz but we don't know it. Please contact us.
[codecarbon INFO @ 12:05:37] CPU Model on constant consumption mode: Intel(R) Xeon(R) CPU @ 2.00GHz
[codecarbon INFO @ 12:05:37] >>> Tracker's metadata:
[codecarbon INFO @ 12:05:37]   Platform system: Linux-5.15.133+-x86_64-with-glibc2.31
[codecarbon INFO @ 12:05:37]   Python version: 3.10.13
[codecarbon INFO @ 12:05:37]   CodeCarbon version: 2.3.4
[codecarbon INFO @ 12:05:37]   Available RAM : 31.358 GB
[codecarbon INFO @ 12:05:37]   CPU count: 4
[codecarbon INFO @ 12:05:37]   CPU model: Intel(R) Xeon(R) CPU @ 2.00GHz
[codecarbon INFO @ 12:05:37]   GPU

In [19]:
%%time
tracker.start()
sample_test_dataset = sample_test_dataset.map(llama2_hs)
sample_test_dataset
co2_emission = tracker.stop()

  0%|          | 0/20 [00:00<?, ?ex/s]

[codecarbon INFO @ 12:05:56] Energy consumed for RAM : 0.000049 kWh. RAM Power : 11.759081840515138 W
[codecarbon INFO @ 12:05:56] Energy consumed for all GPUs : 0.000309 kWh. Total GPU Power : 74.10897936609611 W
[codecarbon INFO @ 12:05:56] Energy consumed for all CPUs : 0.000177 kWh. Total CPU Power : 42.5 W
[codecarbon INFO @ 12:05:56] 0.000535 kWh of electricity used since the beginning.
[codecarbon INFO @ 12:06:11] Energy consumed for RAM : 0.000098 kWh. RAM Power : 11.759081840515138 W
[codecarbon INFO @ 12:06:11] Energy consumed for all GPUs : 0.000618 kWh. Total GPU Power : 74.19354957761215 W
[codecarbon INFO @ 12:06:11] Energy consumed for all CPUs : 0.000354 kWh. Total CPU Power : 42.5 W
[codecarbon INFO @ 12:06:11] 0.001070 kWh of electricity used since the beginning.
[codecarbon INFO @ 12:06:26] Energy consumed for RAM : 0.000147 kWh. RAM Power : 11.759081840515138 W
[codecarbon INFO @ 12:06:26] Energy consumed for all GPUs : 0.000924 kWh. Total GPU Power : 73.57563417305

CPU times: user 1h 7min 32s, sys: 3.92 s, total: 1h 7min 36s
Wall time: 1h 7min 31s


In [20]:
sample_test_dataset["llama2_output"]

[{'text': '#ifndef _BLE_SERVICE_H_\n#define _BLE_SERVICE_H_\n\n#include <Arduino.h>\n#include "ble.h"\n\n#ifdef __cplusplus\nextern "C" {\n#endif\n\n#define BLE_SERVICE_UUID_UUID_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_16_1'},
 {'text': '\n### 1\n\n- 🧑 ở trong 1994\n\n

In [21]:
def check_label(llama2_response):
    keywords = {
        'deregotory': int(2),
        'harmful': int(2),
        "discrimination" : int(2),
        "violence" : int(2),
        'negative': int(2),
        'Negative': int(2),
        "attack" : int(2),
        "slander" : int(2),
        "vulgar" : int(2),
        "offensive" : int(2),
        'non-hate': int(0),
        'Mixed': int(0),
        'neutral': int(0),
        'Neutral': int(0),
        'non-offensive': int(0),
        'positive': int(1),
        'Positive': int(1)

    }
    positions = {keyword: str(llama2_response['llama2_output']).find(keyword) for keyword in keywords}
    valid_positions = {key: pos for key, pos in positions.items() if pos != -1}
    if not valid_positions:
        return {'predicted_label': int(3)}
    first_keyword = min(valid_positions, key=valid_positions.get)
    return {'predicted_label': (keywords[first_keyword])}

In [22]:
sample_test_dataset = sample_test_dataset.map(check_label)
sample_test_dataset

  0%|          | 0/20 [00:00<?, ?ex/s]

Dataset({
    features: ['Data', 'Label', 'llama2_output', 'predicted_label'],
    num_rows: 20
})

In [23]:
sample_test_dataset.to_csv('Llama 2 HS test data.csv')
#co2_emission.to_csv('CO2 emissions.csv')
sample_test_dataset

Creating CSV from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Dataset({
    features: ['Data', 'Label', 'llama2_output', 'predicted_label'],
    num_rows: 20
})

In [24]:
#sample_test_dataset['predicted_label']

In [25]:
predictions= sample_test_dataset['predicted_label']
ground_truth_labels= sample_test_dataset['Label']

In [26]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix, classification_report

accuracy = accuracy_score(ground_truth_labels, predictions)
f1_macro = f1_score(ground_truth_labels, predictions, average='macro')
f1_micro = f1_score(ground_truth_labels, predictions, average='micro')

precision = precision_score(ground_truth_labels, predictions, average="weighted")
recall = recall_score(ground_truth_labels, predictions, average="weighted")
class_report = classification_report(ground_truth_labels, predictions)
conf_matrix = confusion_matrix(ground_truth_labels, predictions)

print("Accuracy:", accuracy)
print("F1 Macro:", f1_macro)
print("F1 Micro:", f1_micro)
print('Precision:', precision)
print("Recall:", recall)
print("Classification Report:\n", class_report)
print("Confusion Matrix: \n", conf_matrix)
print('Total CO2 emissions in grams: \n',co2_emission*1000)

Accuracy: 0.0
F1 Macro: 0.0
F1 Micro: 0.0
Precision: 0.0
Recall: 0.0
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       6.0
           1       0.00      0.00      0.00       6.0
           2       0.00      0.00      0.00       8.0
           3       0.00      0.00      0.00       0.0

    accuracy                           0.00      20.0
   macro avg       0.00      0.00      0.00      20.0
weighted avg       0.00      0.00      0.00      20.0

Confusion Matrix: 
 [[0 0 0 6]
 [0 0 0 6]
 [0 0 0 8]
 [0 0 0 0]]
Total CO2 emissions in grams: 
 41.22618308804181
